host = "0.0.0.0:9090"
env = "prod"
v8_maxcount = 30
v8_lifetime = 3600
js_project_path = "jsproj"
static_url_path = "/static"
internal_api_ip = "127.0.0.1"
internal_api_port = 80
template_name = "ssr.prod.html"
client_cookie = "gossr_id"
redirect_onerror = "/error/404"
ssr_ctx = ["User-Agent","X-Forwarded-For"]

[Log]
debug=false
filenum=20
filesize=256
filename="run"
level="INFO"
dir="/data/log/ssr_logs"
